### ISSUE TITLE
Preprint for html submissions

### ISSUE THREAD

**Issue by essepuntato** [data-science-hub/data-science-hub.github.io#10]
About: "Submitted papers have to be published as a pre-print before reviewing, so reviewers and everybody else are free to share submitted papers"

I think it would be useful to suggest few pointers to preprint servers that accept pure HTML submissions - I had some experience with arXiv and, even if they say to accept html, they really push you to have the PDF...

**Comment by RubenVerborgh** [comment]
Can the right template and a fixed series of steps deliver a consistent PDF? Several command-line utilities generate PDF from HTML.

**Comment by essepuntato** [comment]
Well a way-round would be using [ROCS](http://dasplab.cs.unibo.it/rocs), which is a converter for RASH documents into LaTeX, that can be [installed](https://github.com/essepuntato/rash/tree/master/tools/rocs) on another existing and more Journal-appropriate server, if needed. There is no LaTeX->PDF step implemented there, but it could be added easily.

Otherwise, there is the option of using a fixed (and pretty standard) [ODT template](https://rawgit.com/essepuntato/rash/master/documentation/rash-in-odt.odt) that can be, then, automatically converted into RASH and then to LaTeX by using ROCS (again).

**Comment by tkuhn** [comment]
We plan to make pre-prints available on the journal website as HTML. I rephrased this part a bit: http://datasciencehub.net/features.html

We probably can't enforce CC-BY for pre-prints, as authors of rejected papers might want to resubmit to a non-OA journal...
