### ISSUE TITLE
Review guidelines

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#13]
We also need reviewing guidelines.

**Comment by micheldumontier** [comment]
here's the draft
https://docs.google.com/document/d/1WHTnX5jlOQ7QGp4dyQKb4GWuEkCDJ5u67tHJABLhf-g/edit

**Comment by tkuhn** [comment]
The current version is now on the preliminary website: http://datasciencehub.net/guidelines.html

**Comment by tkuhn** [comment]
We will have to continuously update this, but the current version is good enough for now.
