### ISSUE TITLE
Time given for reviews

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#14]
How much time should be given for reviews?

I don't think there is any evidence that amount of time given correlates with quality of reviews, or even with ratio of late reviews. Therefore, I am in favor of tight deadlines, such as 10 days for reviews.

**Comment by micheldumontier** [comment]
10 days.

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by tkuhn** [comment]
10 days it is. I added that information to the website.
