### ISSUE TITLE
Editoral board special issue as first issue

### ISSUE THREAD

**Issue by essepuntato** [data-science-hub/data-science-hub.github.io#16]
There will be an Editorial board Special Issue as first issue of the journal? It is something I've already seen in the Semantic Web journal, and it seemed it worked quite well as approach. 

What do you think?

**Comment by tkuhn** [comment]
Yes, there will be! We will start sending out invitations very soon! :)

**Comment by tkuhn** [comment]
Done. Invitations are out :)
