### ISSUE TITLE
Which criteria apply to which type of paper

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#17]
We need to define which of the reviewing criteria apply to which type of paper: http://datasciencehub.net/guidelines.html

Position papers and surveys need to be evaluated differently. And invited vision papers should probably be a category on their own.

**Comment by micheldumontier** [comment]
Invited vision papers are position papers. the main criteria are sound argumentation that is evidenced by literature. no new methods or findings required.

**Comment by tkuhn** [comment]
The review criteria are now formulated in a way that applies to all types of papers (except reports, which we will include later on). See issue #24.
