### ISSUE TITLE
Everybody can submit reviews/comments

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#18]
We want to allow everybody to submit reviews and comments, not just solicited reviewers. Concerns were raised by an editorial board member, so let's discuss it here.

**Comment by tkuhn** [comment]
For the following reasons, I think that open reviews and comments is a good idea:

- Even though we don't expect this to become a heavily used feature, just the possibility of submitting reviews for everybody is a very strong signal that we are serious about being open and inclusive.
- The more eyes we have on a paper, the more likely it is that crucial flaws of a paper are spotted. And if somebody wants to help us by pointing out such a flaw, why not allow for it?
- Users will have to login with their ORCID, which will heavily reduce the risk of spam or trolling.

But we will have to instruct editorial board members to tell authors that they don't have to respond to particular additional reviews, if they are not constructive or if there are simply too many of them.

**Comment by micheldumontier** [comment]
agree with this.

**Comment by tkuhn** [comment]
Once logged in via ORCID, everybody can now post comments or reviews.
