### ISSUE TITLE
Pre-prints remain available after rejection

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#19]
We want to make all submitted papers available as pre-prints, and make sure these pre-prints remain available after a decision has been made, also in the case of a rejection. Concerns were raised by an editorial board member, so let's discuss it here.

**Comment by RinkeHoekstra** [comment]
Other journals have a fixed period of time (e.g. one month) for which the preprint of a rejected paper remains online.

**Comment by tkuhn** [comment]
Authors might want to remove their preprints after a rejection, but I think we shouldn't allow for that, for the following reasons:

- We would like to give reviewers more credit for their reviews by making them open and non-anonymous. But a review of a paper that is no longer available is basically worthless. So, out of respect for the work of the reviewers, rejected papers should remain available.
- If authors feel that they might be embarrassed to see their paper online after rejection, then it's probably better if these authors don't submit in the first place.
- Of course, we don't plan to prominently display rejected papers. We want to advocate and show the accepted ones. But if you are looking for a particular submission, you should be able to find it.
- We can remove rejected manuscripts from our website, if the authors upload their paper to an accepted third-party not-for-profit archival institution, like arXiv.org.
- The data about our journal should itself be available for Data Science investigations. To understand peer review, for example, we need to be able to look at all papers, not just the accepted ones.
- It's unusual for a journal to keep rejected papers available, but we want to move forward rather than be a usual journal.

**Comment by tkuhn** [comment]
@RinkeHoekstra Yes, and I think that's a step into the right direction. But why not take a slightly bigger step than what other journals are currently doing?

**Comment by phitzler** [comment]
At the Semantic Web journal we do it as follows: Rejected manuscripts stay online for a minimum of 4 weeks. After 4 weeks (or later), authors can request that their manuscript is depublished, which is then always done. The only thing that then remains public online is the title of the paper (authors not mentioned). 

We established this because rejected authors may want to resubmit to other (lesser) journals after a reject, and would like the new reviewers to be unbiased. Also, in some cases, authors informed us that resubmissions to another journal were immediately rejected with the claim that "the paper is already online on the SWJ site".

**Comment by tkuhn** [comment]
@phitzler Thanks for sharing the experiences with your journal.

So, if we offer authors to remove their manuscript if they upload it to a site like arXiv.org, then the problem of resubmissions should be resolved for virtually all potential journals (see here: https://en.wikipedia.org/wiki/List_of_academic_journals_by_preprint_policy). Furthermore, it would allow authors to resubmit right away, without waiting 4 weeks.

And if authors are worried that the new reviewers might be biased by the open reviews still available on our website, they can simply change the title of the new submission, which will make it very unlikely that the new reviewers stumble upon the old reviews.

That would keep all the benefits mentioned above, without disproportionate negative consequences for the authors. Or am I missing something?

**Comment by phitzler** [comment]
I think this is worth a shot, but probably needs watching. At SWJ we kept having to make tweaks to the process during the first few years as problems came up. But I don't see an obvious problem with your suggestion, other than that you'd rely on a third-party service (arXiv). You may also need a tweak to the review management system in this case, though, I think currently you cannot unpublish the manuscript without unpublishing the reviews (but I may be wrong on this).
