### ISSUE TITLE
Everybody needs an ORCID identifier

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#21]
We plan to require everybody - editorial board members, authors, co-authors, and reviewers - to provide thier ORCID identifiers. Concerns were raised by an editorial board member, so let's discuss it here.

**Comment by tkuhn** [comment]
I don't see a good reason for not requiring ORCIDs from everybody. (ORCIDs won't be disclosed if reviewers choose to be anonymous, of course.) It's super easy to get an ORCID for those who don't have one yet, and ORCIDs are really standard and well-accepted nowadays.

**Comment by micheldumontier** [comment]
agreed. i think it's a must.
