### ISSUE TITLE
Define details of paper submission form

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#26]
We also need to define the details of the paper submission form. It should include:

- disclaimer that paper will be made available as preprint (and stay available after rejection)
- remind authors of reproducibility and data publishing requirements
- maybe ask authors about semantic publishing features

**Comment by micheldumontier** [comment]
guidelines for tables and figure preparation?
guidance or provision of document template?

**Comment by tkuhn** [comment]
Here is a first draft: https://github.com/data-science-hub/files/blob/master/submission-form/version1-draft.txt

**Comment by tkuhn** [comment]
This is the first version of the paper submission form that we are going to use: https://github.com/data-science-hub/files/blob/master/forms/submission-form-v1.0.txt
