### ISSUE TITLE
Asking reviewers to judge the length of the manuscript

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#27]
What do you think about asking reviewers to judge the length of the manuscript? Some research really needs a considerable number of pages to be explained, but in other cases a much lower number of pages would be sufficient. However, page or word limits tend to be exhausted no matter what. So, I suggest to include this option in the reviewing form:

> Length of the manuscript *?
> - This manuscript is too long for what it presents and should therefore be
>   considerably shortened (below the general length limit)
> - The length of this manuscript is about right
> - The authors need to elaborate more on certain aspects and the manuscript
>   should therefore be extended (if the general length limit is already reached,
>   I urge the editor to allow for an exception)

**Comment by micheldumontier** [comment]
sure that seems like it's relatively lightweight .... we can try it out.
