### ISSUE TITLE
Extended versions

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#36]
I just added the following section to the author instructions to address submissions that are extended versions of conference/workshop papers:

> We accept extended versions of works previously published at workshops or conferences under the following conditions:
> 
> - The previous publication is clearly and prominently indicated and referenced
> - The additions and differences are described in the introduction
> - At least 25% of the content of the extended version are new
> - The extended version covers significant additional elements, and is not just a more verbose version of the previous content
> 
> It is furthermore the authors’ responsibility to ensure that the publication of the extended version complies with the requirements (including copyright) of the previous publisher.

Let us know if you have comments on this.

**Comment by micheldumontier** [comment]
that works for me tobias!
