### ISSUE TITLE
Scientific context

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#4]
Feedback from editorial board member:

> Do you think the title or streamer or at least the bullet points on data mining/ML/etc. should explicitly mention the scientific context? Otherwise you may see lots of submissions that address e.g. marketing and other business analytics contexts, or indeed cloud computing or generic “big data” topics. I see loads of CFPs for things that address data science and big data that include topics that are probably out of scope for this.

**Comment by jodischneider** [comment]
+1 to this

Maybe need to tie in more concretely with "physical, biological, and digital systems, gain insight into human social and economic behavior, and design new solutions for the future". So far it says "scientific data mining, machine learning, and Big Data analytics"

Similarly these bullet points might specify a scientific context:
- data wrangling, integration, provenance
- trend analysis, prediction, and visualization
- crowdsourcing and collaboration
- corroboration, validation, trust, and reproducibility
- scalable computing, analysis, and learning
- smart and semantic web services, executable workflows
- analytics, intelligence, and real time decision making

**Comment by tkuhn** [comment]
I now added emphasis of the scientific aspects for each of these points.
