### ISSUE TITLE
Specifics on HTML submissions

### ISSUE THREAD

**Issue by tkuhn** [data-science-hub/data-science-hub.github.io#6]
Provide details on how authors can write and submit articles in HTML.

**Comment by tkuhn** [comment]
Additional thought: Reduced article processing fee for HTML submissions (once we actually have a fee, after 1 year or so).

**Comment by essepuntato** [comment]
I can provide a full description for RASH, if needed.

In addition, I may also include a stylesheet in ROCS (http://dasplab.cs.unibo.it/rocs) so as to convert it into LaTeX according to the IOS press template - that could be useful from a publisher side I think.

**Comment by tkuhn** [comment]
I think a short description of RASH with some links of how to get started would be great!

Is there a translation of RASH to JATS? I think that's what the publisher would be really happy about.

We should make submissions in HTML available in their HTML format. For that, the two-column format of IOS Press is probably not a good choice...

**Comment by essepuntato** [comment]
I will prepare an intro text for RASH then. And I see what I can do for a RASH to JATS conversion. Do you have some exemplar JATS they use?

**Comment by tkuhn** [comment]
Great, thank you!

Wrt JATS, we should probably discuss this at some point directly with the IOS Press people. I can start a separate email discussion with you and them, if you like. But there is no hurry at all at the moment, so we can also postpone it.

**Comment by essepuntato** [comment]
This is a draft text for RASH.

## RASH description

The [_Research Articles in Simplified HTML_ (_RASH_)](https://github.com/essepuntato/rash/) ([doc](https://rawgit.com/essepuntato/rash/master/documentation/index.html), [paper](https://rawgit.com/essepuntato/rash/master/papers/rash-demo-iswc2015.html)) is a markup language that restricts the use of HTML elements to only 32 elements for writing academic research articles. It is possible to includes also RDFa annotations within any element of the language and other RDF statements in Turtle, JSON-LD and RDF/XML format by using the appropriate tag `script`.

[Guidelines for OpenOffice](https://rawgit.com/essepuntato/rash/master/documentation/rash-in-odt.odt) have been developed so as to write a scholarly paper by using the basic features available in OpenOffice Writer, in a way that it can be converted into RASH by means of the [_RASH Online Conversion Service_ (_ROCS_)](http://dasplab.cs.unibo.it/rocs) ([src](https://github.com/essepuntato/rash/tree/master/tools/rocs), [paper](https://rawgit.com/essepuntato/rash/master/papers/rash-poster-www2016.html)).

Other links:
- [papers](https://github.com/essepuntato/rash#papers-introducing-the-rash-framework) introducing RASH and its Framework
- [venues](https://github.com/essepuntato/rash#venues-that-have-adopted-rash-as-submission-format) that have adopted RASH as HTML-based submission format
- [published papers](https://github.com/essepuntato/rash#rash-papers-accepted-in-scholarly-venues) presented in scholarly venues and available in RASH

## Version in Markdown

<pre>
The [*Research Articles in Simplified HTML* (*RASH*)](https://github.com/essepuntato/rash/) ([doc](https://rawgit.com/essepuntato/rash/master/documentation/index.html), [paper](https://rawgit.com/essepuntato/rash/master/papers/rash-demo-iswc2015.html)) is a markup language that restricts the use of HTML elements to only 32 elements for writing academic research articles. It is possible to includes also RDFa annotations within any element of the language and other RDF statements in Turtle, JSON-LD and RDF/XML format by using the appropriate tag `script`.
[Guidelines for OpenOffice](https://rawgit.com/essepuntato/rash/master/documentation/rash-in-odt.odt) have been developed so as to write a scholarly paper by using the basic features available in OpenOffice Writer, in a way that it can be converted into RASH by means of the [*RASH Online Conversion Service* (*ROCS*)](http://dasplab.cs.unibo.it/rocs) ([src](https://github.com/essepuntato/rash/tree/master/tools/rocs), [paper](https://rawgit.com/essepuntato/rash/master/papers/rash-poster-www2016.html)).
Other links:
* [papers](https://github.com/essepuntato/rash#papers-introducing-the-rash-framework) introducing RASH and its Framework
* [venues](https://github.com/essepuntato/rash#venues-that-have-adopted-rash-as-submission-format) that have adopted RASH as HTML-based submission format
* [published papers](https://github.com/essepuntato/rash#rash-papers-accepted-in-scholarly-venues) presented in scholarly venues and available in RASH
</pre>

**Comment by tkuhn** [comment]
Great, thank you! We'll use that for the submission instruction page.

**Comment by RubenVerborgh** [comment]
We might need to go further and provide a template?

**Comment by essepuntato** [comment]
Well, a [generic template](https://github.com/essepuntato/rash/blob/master/template.html) is actually available. It can be also found in the convenient [ZIP archive](https://rawgit.com/essepuntato/rash/master/rash.zip) containing the whole RASH package.

Then, an additional option would be to have an "official" RASH template released by the Journal. That may be an option indeed.

**Comment by tkuhn** [comment]
Apparently, the current internal process at IOS Press is to generate JATS (XML) from LaTeX. If JATS could be generated directly from HTML that would be great for them (and other publishers, I suppose).

I am not sure to what degree JATS has support for semantic markup or the like...

In any case could a HTML>JATS conversion be a very good selling point to convince publishers to support HTML submissions.

**Comment by maarteniospress** [comment]
Hi, This is Maarten from IOS Press. What Tobias writes is true, we currently produce journal articles in JATS 1.0. To get some idea [here](https://github.com/data-science-hub/data-science-hub.github.io/files/354408/sw-7-4-sw180.zip) you can download an example journal article package. For us it is helpful when authors prepare an article in LaTeX (but most used is MsWord without any tagging) but I guess that any kind of structured document would help our production office to convert into JATS. If we can get JATS XML already as input so much the better.

**Comment by essepuntato** [comment]
Hi Maarten,

I've just checked the JATS XML you provided, and it is a structure that is quite reasonable to obtain from RASH. I would try to work on the converter as soon as I can.

I'm not fully convinced that the authors will do an additional extra work for producing the JATS (even if it can be done through an automatic process), but such a converter would be useful even if you will take care of the conversion, wouldn't be?

The only real issue I see are the math formulas that you, correctly, handle in MathML in JATS, but that can be potentially written by the authors in different ways in the source HTML-RASH. Something to think about...

**Comment by maarteniospress** [comment]
Yes I don't think we should ask authors to do any kind of conversion, we would have to take care of that. Do I understand correctly there already is a conversion to LaTeX possible? If yes that would also work (if the math can also included in the HTML-RASH and be converted) but still a converter to JATS I think would be useful, maybe not specifically for us but in general.

**Comment by essepuntato** [comment]
I fully agree that a converter into JATS is a useful feature to add, indeed - and I hope to add it to the ROCS service soon.

For what concern LaTeX, yes: there are already several XSLT developed that convert RASH into LaTeX. I still have to develop the one for the IOS press journal style class, but I'm working on it in these days since I have a specific need in this sense. In this case, I've already implemented MathML to LaTeX conversion through a quite good XSLT I've found available only. Thus the formulas should not be an issue in this case.

**Comment by tkuhn** [comment]
Guidelines of how to write papers in HTML using RASH can now be found here: http://datasciencehub.net/guidelines.html

**Comment by csarven** [comment]
I'm not sure how much room you have to mention _dokieli_, but if you can squeeze in the following, that'd be great:

``` html
<a href="https://github.com/linkeddata/dokieli">dokieli</a> is a client-side editor for decentralised article publishing in HTML+RDFa, annotations and social interactions, compliant with the <a href="https://linkedresearch.org/">Linked Research</a> initiative. There are a variety of <a href="https://github.com/linkeddata/dokieli/wiki#examples-in-the-wild">examples in the wild</a>, where the <a href="https://dokie.li/lncs-splnproc">LNCS</a> or <a href="https://dokie.li/acm-sigproc-sp">ACM</a> author guidelines</a> as a template may be particularly useful.
```

Feel free to edit to suit your needs. Thanks.

**Comment by tkuhn** [comment]
Yes! Thank you. I just wanted to get back to you wrt that.

I added it to the website with slight modifications. I hope it looks good to you.

**Comment by csarven** [comment]
Looks good to me, thank you.
