### ISSUE TITLE
Number of words vs number of pages

### ISSUE THREAD

**Issue by essepuntato** [data-science-hub/data-science-hub.github.io#8]
Using the number of words as constraint for the various kinds of papers is format independent (it holds for both HTML and Word) and, for HTML submission, it doesn't oblige one to use particular CSS for visualising the article according to a particular way.

**Comment by tkuhn** [comment]
Good point. Maybe even number of characters, which is more straightforward to count?

**Comment by essepuntato** [comment]
I'll suggest to do what the other journals usually do, which is counting words - they are quite easy to count, as well as characters of course. 

The only think you have also to consider is how to count figures and tables. Usually a standard size in words is associated to these elements (e.g. 300 words per figure); other times some journals limit the number of figures and tables that one can use (e.g. max 3 figures). It really depends on you, they are all valuable options.

**Comment by tkuhn** [comment]
I agree, words are easy to count, but there are many different ways how they can be counted (how many words are "e.g. computer-aided"?). Character count is a much more precise measure in this sense, I believe. But I agree, such a word or character count is better than page count.

**Comment by jodischneider** [comment]
+1 to word count. I agree with standard "word count" (300 words sounds reasonable to me) for figures. Let's avoid a maximum limitation on the number of figures (this should generally be self-limiting).

**Comment by RubenVerborgh** [comment]
+1 to word count. It might be not as precise as character count depending on the counting method, but I don't believe the _exact_ count is that important.

**Comment by tkuhn** [comment]
Done. Word count limits are shown here: http://datasciencehub.net/guidelines.html
